UMAprotocol/optimistic-oracle-dapp-v2

.eslintrc.json, package.json, public/assets/check.svg, public/assets/search.svg, src/components/Filters/CheckboxDropdown.tsx, src/components/Filters/Dropdown.tsx, src/components/Filters/Filters.tsx, src/components/Filters/Search.tsx, src/components/Layout.tsx, src/components/index.ts, src/stories/Filters.stories.tsx, yarn.lock
Signed-off-by: ryanwolhuter <dev@ryanwolhuter.com>
Add UI components for the following features:
* search bar input
* checkbox dropdowns for filters
* add search bar input
* add checkbox dropdown component
https://63d101d13121a53332f6218c-pgtkxtdelc.chromatic.com/?path=/story/stories-filters--default
=> feat: filters

libs/src/constants.ts, libs/src/oracle2/services/gql/factory.ts, libs/src/oracle2/services/gql/utils.ts, libs/src/oracle2/types.ts, src/components/Panel/Panel.tsx, src/constants/env.ts, src/helpers/converters.ts, src/helpers/util.ts, src/hooks/actions.ts, src/hooks/index.ts, src/stories/mocks.tsx, src/types/ui.ts
we need an interface to be able to know what actions we can take, and wrap those actions based on what the current context is
this adds an action "hook" which dynamically adds things you can do based on the state of the app. in this case its exposing functions to fetch token info, balance and approval, and has a stub for requesting approval from token contract. this may go through further changes to get the api right.
=> feat: add token approval and interface for actions

libs/src/constants.ts, libs/src/oracle2/services/index.ts, libs/src/oracle2/services/oracleSkinny/gql/factory.ts, libs/src/oracle2/services/oracleSkinny/gql/index.ts, libs/src/oracle2/services/oracleSkinny/gql/queries.ts, libs/src/oracle2/services/oracleSkinny/gql/utils.ts, libs/src/oracle2/services/oracleSkinny/index.ts, libs/src/oracle2/services/oracleV3/gql/queries.ts, libs/src/oracle2/services/oracles/factory.ts
skinny oo was launched on the graph, we want to integrate it into app
this adds the only known skinny gql deployment, and also found an issue loading v3 requests, so that fix is in this pr
=> feat: add skinny oo, fix v2 query

package.json, public/assets/icons/failure.svg, public/assets/icons/success.svg, public/mockServiceWorker.js, src/components/Layout.tsx, src/components/LoadingSpinner.tsx, src/components/Notification.tsx, src/components/Notifications.tsx, src/components/index.ts, src/constants/styles/colors.ts, src/contexts/NotificationsContext.tsx, src/contexts/index.ts, src/hooks/contexts.ts, src/pages/_app.tsx, src/stories/Notifications.stories.tsx, src/stories/mocks.tsx, src/stories/pages/Propose.stories.tsx, src/stories/pages/Settled.stories.tsx, src/stories/pages/Verify.stories.tsx, src/stories/pages/shared.tsx, src/stories/pages/types.ts, src/types/ui.ts, yarn.lock
we need to be able to show transaction notifications
this basically copies in the voter notification system with minimal changes, this does remove the idea of a transaction hash, which is replaced by a link, and also changes ids to strings or numbers. this is untested, and will be integrated in a different pr.
=> feat: vote notification system copied in

shared/utils/graphql.ts
we were incorrectly checking expiry time, using seconds instead of ms
just turn the value in seconds to ms
=> fix: compare time as ms

.storybook/preview.tsx, package.json, scripts/approvedIdentifiersTableParser.ts, shared/utils/ethers.ts, shared/utils/graphql.ts, src/components/Notification.tsx, src/components/OracleQueryList/Item.tsx, src/components/OracleQueryTable/Row.tsx, src/components/Panel/Panel.tsx, src/contexts/NotificationsContext.tsx, src/contexts/OracleDataContext.tsx, src/contexts/PanelContext.tsx, src/data/approvedIdentifiersTable.json, src/data/approvedIdentifiersTable.ts, src/helpers/converters.ts, src/helpers/notifications.ts, src/hooks/actions.tsx, src/hooks/helpers.ts, src/hooks/page.ts, src/stories/mocks.tsx, src/stories/pages/shared.tsx, src/types/ui.ts, tsconfig.json, yarn.lock
We have a "more information" section in the panel where we display miscellaneous info. Populate that section with details from requests and assertions.
* add `makeMoreInformationList` function to converters
* add `makeBlockExplorerLink` helper that handles all supported chains
* port `approvedIdentifiersTable` from voter dapp
* move request link url logic to panel component
=> feat: wire up more information section

package.json, src/components/Header/VoteTicker.tsx, src/pages/api/_common.ts, src/pages/api/get-voting-info.ts, yarn.lock
we are seeing errors in console due to missing serverless function, and vote ticker feature not working
this copies in the latest code from uma.xyz related to vote ticker. it now shows in ui
=> feat: add vote ticker function

src/components/Panel/Panel.tsx, src/contexts/PanelContext.tsx, src/hooks/handleQueryInUrl.ts
We want to close the panel when the user clicks the back button in the browser.
=> fix: close panel on pop state

src/hooks/actions.tsx
action button keeps enabling while tx is being mined
this is due to different timing between waiting on tx wtih ethers and the wagmi hook to watch tx hash.  we want to use the data returned from wagmi hook to disable button once tx is mined.  this required some changes to the dependent calls, as certain things needed to be reset when changing which query we are looking at.
=> fix: ensure buttons stay disabled during tx confirm

src/components/Currency.tsx, src/components/OracleQueryList/ItemDetails.tsx, src/components/OracleQueryTable/Headers.tsx, src/components/OracleQueryTable/LoadingRow.tsx, src/components/OracleQueryTable/VerifyCells.tsx, src/components/OracleQueryTable/style.tsx, src/stories/mocks.tsx
we want to see bond on verify page
adds another column for bond on verify table
adds bond to verify in mobile query list
**[Story](https://63d101d13121a53332f6218c-xzubtehniu.chromatic.com/?path=/story/pages-verify--default)**
=> feat: add bond for verify table

src/components/Layout.tsx, src/components/LegacyDappLinkBanner.tsx
Add legacy dapp banner at the top of the page. Clicking the close button hides it with local storage.
=> feat: add legacy dapp link banner

libs/src/oracle-sdk-v2/services/oraclev1/gql/queries.ts, src/contexts/OracleDataContext.tsx
it seems lke we are missing some requests
this is due to missing some values from query, but we are limited to 1000 requests
=> feat: increase gql query size, log errors

libs/src/constants.ts, shared/constants/oracle.ts, shared/utils/ethers.ts, src/constants/env.ts
Fixes: https://linear.app/uma/issue/UMA-2396/add-core-to-oo-app
Adds core mainnet. We still would need to update rainbowkit dependencies in order to allow connect to core and post proposals/disputes.
=> feat: add core network

libs/src/constants.ts, shared/constants/oracle.ts, shared/utils/ethers.ts, src/constants/env.ts, src/constants/wallet.ts, src/hooks/actions.tsx
Adds support for Sepolia testnet
Fixes: https://linear.app/uma/issue/UMA-2451/update-oracle-dapp-to-support-sepolia
=> feat: support sepolia

libs/src/constants.ts, shared/constants/oracle.ts, shared/utils/ethers.ts, src/constants/env.ts, src/constants/wallet.ts
we want to enable base in the ui
add required envs and constants.  envs have been added to vercel for the prod deployment.
=> feat: add base envs and constants

libs/src/constants.ts, shared/constants/oracle.ts, shared/utils/ethers.ts, src/constants/customChains.ts, src/constants/env.ts, src/constants/icons.tsx, src/constants/wallet.ts
Fixes: https://linear.app/uma/issue/UMA-2497/update-oracle-dapp-supporting-polygon-amoy
=> feat: support polygon amoy testnet

vercel.json
This PR fix some http headers, to prevent malicious use of our website
=> Fix: Update headers

libs/src/constants.ts, libs/src/utils.ts, shared/constants/oracle.ts, shared/utils/ethers.ts, src/constants/customChains.ts, src/constants/env.ts, src/constants/wallet.ts
=> add blast sepolia config

src/constants/env.ts
Not seeing any v2 requests, not parsing config correctly.
There _are v2 requests here: https://sepolia.blastscan.io/address/0xD8c6dD978a3768F7DDfE3A9aAD2c3Fd75Fa9B6Fd
=> HOTFIX: blast sepolia config

libs/src/constants.ts, libs/src/oracle-sdk-v2/client.ts, libs/src/oracle-sdk-v2/services/oraclev2/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/factory.ts, libs/src/utils.ts, shared/constants/oracle.ts, shared/utils/ethers.ts, src/constants/customChains.ts, src/constants/env.ts, src/constants/wallet.ts, src/contexts/OracleDataContext.tsx
closes UMA-2790
@daywiss 
The one and only AssertionMade event emitted by this OOv3 contract is currently over 200_000 blocks old. 
If you change the max lookback to 300_000, then the app does find it, update it from tx receipt etc, but for some reason does not show up in the UI!
=> support story odyssey

src/hooks/useQueryInSearchParams.ts
polymarket sents the wrong event index by 1, so their links break when we try to make the url filter more strict
We attempt to match teh most likely request as long as the transaction hash matches a request. If event index does not match, we rank the closest one to the event index specified.  This may give false positives, matching a request that does not exactly match both request hash and event index, but this is a tradeoff to fix the polymarket links for now, until they can update their side.
=> fix: rank transactions if event index does not match exactly

src/components/Layout.tsx, src/contexts/OracleDataContext.tsx
we dont wnat to point to legacy dapp anymore
If both graph and web3 fallbacks fail, point to cli dispute tool
=> improve: link to dispute cli tool if no data available

src/hooks/actions.tsx
=> handle settle reverts

src/helpers/util.ts
We need to be able to encode and decode multiple query values
This adds an encode/decode function, tested separately because could not get testing to work correctly in this repo
these pass
```ts
describe("format and parse multiple query price", () => {
it("should format and then parse input values correctly", () => {
const inputValues = ["10", "20", "30", "40"];
const formattedPrice = formatMultipleQueryPrice(inputValues);
const parsedValues = parseMultipleQueryPrice(
formattedPrice,
inputValues.length
);
expect(parsedValues).toEqual(inputValues);
});
it("should handle edge case of maximum input values", () => {
const inputValues = ["0", "0", "0", "0", "0", "0", "0"];
const formattedPrice = formatMultipleQueryPrice(inputValues);
const parsedValues = parseMultipleQueryPrice( …
```
=> feat: add mq format and parsing

src/helpers/converters.ts
price encoding/decoding changed
Uses the functions in the spec to encode/decode MQ requests
=> fix: change encoding to match updated umip spec

src/components/DecimalInput.tsx, src/components/OracleQueryTable/Row.tsx, src/components/OracleQueryTable/SettledCells.tsx, src/components/OracleQueryTable/style.tsx, src/components/Panel/Actions/Actions.tsx, src/components/Panel/Actions/Details.tsx, src/components/Panel/Actions/ProposeInput.tsx, src/components/Panel/style.tsx, src/helpers/converters.ts, src/helpers/util.ts, src/hooks/actions.tsx, src/hooks/proposePriceInput.ts
UI work for MULTIPLE_VALUES identifier
TODO
=> Add UI components for multiple values

src/components/OracleQueryTable/Row.tsx, src/components/Panel/Actions/Actions.tsx, src/components/RadioDropdown.tsx, src/helpers/converters.ts, src/helpers/queryParsing.ts, src/hooks/proposePriceInput.ts, src/types/ui.ts
after lee's testing he found several issues we want to fix
this fixes a few issues:
1. do not input 0's in fields before user input
2. do not crash if user inputs invalid inputs
3. fixes issue with scaling proposed answer incorrectly 
4. fixes issue when changing between different mq requests, side bar properly updates
=> fix: various issues with multiple value input

libs/src/constants.ts, src/components/Checkbox.tsx, src/components/DecimalInput.tsx, src/components/OracleQueryTable/VerifyCells.tsx, src/components/Panel/Actions/Actions.tsx, src/components/Panel/Actions/Message.tsx, src/components/Panel/Actions/PrimaryActionButton.tsx, src/components/Panel/Actions/ProposeInput.tsx, src/components/Panel/Title.tsx, src/components/Panel/style.tsx, src/components/Tooltip.tsx, src/helpers/converters.ts, src/helpers/util.ts, src/helpers/validators.ts, src/hooks/actions.tsx, src/hooks/proposePriceInput.ts
Fixes multiple issues/improvements with Multiple Value support.
closes UMA-2824
closes UMA-2822
closes UMA-2825
closes UMA-2816
closes UMA-2821
=> WIP: UI fixes

src/components/OracleQueryTable/SettledCells.tsx, src/components/OracleQueryTable/VerifyCells.tsx, src/components/Panel/Actions/Actions.tsx, src/helpers/validators.ts, src/hooks/actions.tsx
closes UMA-2833
closes UMA-2832
=> Multiple values fixes

src/helpers/converters.ts
=> attempt to parse title description from v3 claim

libs/src/utils.ts, src/constants/earlyRequestMagicNumber.ts
=> correctly check for early request BN

src/components/Panel/ProposerWhitelist.tsx, src/hooks/useProposerWhitelist.ts
closes UMA-2929
closes UMA-2928
=> feat: handles disabled & empty whitelists

src/components/Banners/Banner.tsx, src/components/Banners/Banners.tsx, src/components/Banners/ErrorBanner.tsx, src/components/Banners/ManagedOracleBanner.tsx, src/components/Banners/index.ts, src/components/Layout.tsx, src/components/Link.tsx, src/components/index.ts, src/constants/env.ts, src/hooks/useQueryInSearchParams.ts
closes UMA-2932
- Organized all banners into `Banners.tsx` component.
- Created managed OO Banner, shown/hidden with env var.
- Added minimal Link component
=> feat: managed oracle banner
