UMAprotocol/optimistic-oracle-dapp-v2

libs/src/oracle2/index.ts, libs/src/oracle2/types.ts
Signed-off-by: david <david@umaproject.org>
We want to standardize the data layer to be able to plugin multiple sources to the frontend. This allows us to support gql and web3 querying for data.
This just provides types that we can build to, including standard oracle request type, and client/server interfaces. Frontend could theoretically start building towards this.
=> feat: add basic coms interface for oracle client/server

libs/package.json, libs/src/oracle2/client.ts, libs/src/oracle2/index.ts, libs/src/oracle2/services/gql/factory.ts, libs/src/oracle2/services/gql/index.ts, libs/src/oracle2/services/gql/oracleV1.ts, libs/src/oracle2/services/gql/utils.ts, libs/src/oracle2/services/index.ts, libs/src/oracle2/types.ts, libs/yarn.lock, package.json, src/pages/_app.tsx, yarn.lock
We need an implementation of our data interface connecting to a real gql endpoint. 
This adds a hard coded goerli gql service and example of using it in a client in the app. We still need some environment vars, and implementations for v2 and skinny data, and eventually non gql data.
=> feat: add v1 oracle request client and example

package.json, src/constants/env.ts, src/hooks/queries.ts, src/pages/_app.tsx, src/stories/VoteTicker.stories.tsx, yarn.lock
Signed-off-by: david <david@umaproject.org>
oracle client configs could be pretty complicated, we want to make sure the app has a way to import and validate complex configuration. 
this is a breaking change, but the app will now parse and validate the config, which must be imported as `import {config} from 'constants'`, as opposed to previously just importing the specific value you wanted.
=> improve: add env parsing to app config

public/assets/icons/close.svg, src/components/ErrorBanner.tsx, src/components/ErrorMessage.tsx, src/components/GlobalStyle.tsx, src/components/index.ts, src/constants/styles/fonts.ts, src/constants/wallet.ts, src/contexts/ErrorContext.tsx, src/contexts/index.ts, src/helpers/ethers.ts, src/hooks/contexts.ts, src/pages/_app.tsx, src/stories/ErrorBanner.stories.tsx, src/types/ui.ts, tsconfig.json
Add an error banner component with an associated context. I've elected to keep this context separate from the errors that may show in the panel because I expect that we will handle the error states of actions that the user takes in the functions that transform data for the UI. This banner and context is only intended for showing global errors for things like the graph not working or the user being connected to an unsupported network.
**[Story](https://63d101d13121a53332f6218c-jukricodil.chromatic.com/?path=/story/stories-errorbanner--no-messages)**
* add error banner component
* add error context
=> feat: error banner

src/stories/pages/Pages.stories.tsx
The page stories need to be wrapped in the panel context in order for the panel to show.
Add panel context to page stories wrapper
=> fix: add panel context to page stories

src/hooks/index.ts, src/hooks/page.ts, src/pages/index.tsx, src/pages/propose.tsx, src/pages/settled.tsx, src/types/ui.ts
We want to create an api for the app that makes it clean to render according to design
rather than try to implement functionality, this defines the data that we will need for each part of the UI only at the page level. We can fill in this data in subsequent PRs. This also abstracts the page data into a hook which can also be used for eventually filling in the needed data.
=> feat: add full UI interface, page hook

libs/src/constants.ts, libs/src/oracle2/services/oracleV1/gql/factory.ts, libs/src/oracle2/services/oracleV1/gql/utils.ts, libs/src/oracle2/services/oracles/factory.ts, src/constants/env.ts, src/helpers/converters.ts
we want to add oracle v2 gql endpoints to app now that its available
This re-uses the v1 service, afaik the data structures are the same, and adds the env config to enable it
=> feat: add oracle v2 gql data

src/constants/env.ts
We want app to avoid runtime errors if its misconfigured, and instead fail with a descriptive error
this checks that if we have a subgraph enabled on a chain, we also have a equivalent provider for that chain
if misconfigured an error will throw
=> feat: add dependency check for provider config

libs/src/constants.ts
some of these addresses were wrong, taken from subgraph manifests
went through and verified all hard coded addresses matched latest manifest in subgraph repo https://github.com/UMAprotocol/subgraphs
=> fix: go through and fix mismatch addresses

shared/constants/abi.ts, src/helpers/converters.ts, src/hooks/actions.tsx, src/types/ui.ts
skinny oo contract interactions need to be added
skinny oo contract mutations require the entire request body, which needs to be formatted based on its latest state. this adds the utilities to do this and attempts to create the action functions for this.  there were issues building when passing abis into wagmi, so those lines were disabled for typescript.
=> feat: add skinny oo contract interactions

src/components/Panel/Panel.tsx, src/components/index.ts, src/contexts/OracleDataContext.tsx, src/helpers/converters.ts, src/hooks/actions.tsx, src/types/ui.ts
The panel button was limited to just disputing/proposing/settling, etc, but we also need to connect and switch chains.
this refactors the actions hook to return a button state directly for rendering in the panel. this moves much of the business logic into the action hook and removes some from the panel itself. the button can now respond more dynamically to things like waiting on user, submitting transaction, checking user balance, approvals, etc, and adjust when its disabled, or what message is shown.
there are still issues with transactions showing errors in the panel, which will need to be fixed in new  prs.
=> feat: allow action button to connect and switch chains

src/components/Filters/Filters.tsx, src/components/Layout.tsx, src/components/OracleQueries.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/propose.tsx, src/pages/settled.tsx, src/stories/Filters.stories.tsx, src/stories/OracleQueries.stories.tsx
We want to persist the filter selection on different pages.
* Move filters component to shared layout which is preserved on page changes
* Get the props needed for filters and queries with the page hook
=> fix: switching between different tabs clears filters

src/components/Filters/Filters.tsx, src/components/Filters/Search.tsx, src/components/Layout.tsx, src/components/OracleQueries.tsx, src/constants/filters.ts, src/contexts/FilterAndSearchContext.tsx, src/contexts/PageContext.tsx, src/contexts/index.ts, src/helpers/util.ts, src/hooks/contexts.ts, src/hooks/filters.ts, src/hooks/handleQueryInUrl.ts, src/hooks/index.ts, src/hooks/page.ts, src/hooks/queriesForCurrentPage.ts, src/pages/_app.tsx, src/pages/index.tsx, src/pages/propose.tsx, src/pages/settled.tsx, src/stories/Filters.stories.tsx, src/stories/pages/shared.tsx
There are some bugs in the filtering logic now that we're sharing them across pages. These come about mostly because we are storing the filtering data in a hook, which is being invoked multiple times on different pages. This is solved by lifting this state up into a context and providing that state in the hook instead. The hook can then be invoked wherever.
Another difficulty was passing the page we're on to the filters and making sure that the filters are operating on the right queries. This is solved by removing lifting this state up in a context as well. Now pages explicitly set the "page" value when they are navigated to, and the dependency on the url is removed (helpful for future tasks too).
Finally, the counting logic in the filters was wrong and lead to double counting of entries …
=> fix: wrong entries and double counting in filters

src/contexts/OracleDataContext.tsx, src/helpers/util.ts
We want the queries on each page to be sorted by date.
* Add sort by date util
* Sort `verify`, `propose`, and `settled` queries by date whenever we add new queries to the list
=> feat: sort queries by date

shared/types/graphql.ts, shared/types/oracle.ts, shared/utils/graphql.ts, src/helpers/converters.ts, src/types/ui.ts
the shared types for requests and assertions does not work for web3 data, because these queries cannot gaurantee all the properties required.
this makes more properties optional for requests and assertions so that we can issue partial updates from sources other than the graph.  web3 data may only be dealing with a subset of events, and build an incomplete picture of an oracle request, or may be dealing with calls to contract which may only return partial data, so we need to ensure these types respect that.
=> improve: refac request/assertion types to have more partial vals

src/hooks/filters.ts
When we change pages, its possible that there are items from previous filter selections that have no entries on the new page. Previously I was simply clearing those away and removing those filter options. This caused a problem where the filter selection state is lost when navigating to a page that does actually have queries for that option.
* When we make our filter entries, we use the old state as the basis and set all the existing counts to zero.
=> fix: set all counts for existing filters to zero on change

libs/src/clients/index.ts, libs/src/clients/optimisticOracleV3/client.ts, libs/src/clients/optimisticOracleV3/index.ts, libs/src/oracle-sdk-v2/services/index.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/index.ts, shared/types/oracle.ts, src/components/OracleQueryList/ItemDetails.tsx, src/components/OracleQueryTable/VerifyCells.tsx, src/constants/env.ts, src/contexts/OracleDataContext.tsx, src/helpers/converters.ts, src/helpers/util.ts, src/hooks/actions.tsx, src/types/ui.ts
we want to have state updates when user submits txs that change oracle v3 queries
this does a lot of similar things to the v1 receipt update logic, but we needed to specifically add v3 event to state parsers since we didnt have those from the original sdk. we also have to loosen the UI types because there is some data that is not gauranteed when parsing from events.
=> feat: add v3 receipt parsing

libs/src/oracle-sdk-v2/services/oraclev1/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/factory.ts, libs/src/utils.ts, src/contexts/OracleDataContext.tsx, src/contexts/PanelContext.tsx, src/helpers/converters.ts, src/hooks/actions.tsx, src/types/ui.ts, yarn.lock
settle button not showing up for verify tab which were expired.
testing this feature, ended up finding some more critical bugs:
1. updates to query state were not being reflected in panel - changed how panel references query state
2. once this was fixed, transactions in the action hook would loop infinitely, due to watching query state with transaction data, removed this dependency, but this may have unknown consequences
3. merged data from receipt would override previous data even if undefined, this was due to converters always exporting keys even when the values were undefined, causing overrides.  refactored converters to only return keys where data exists
finally the button is enabled now to "settle" when a vote had gone through liveness
=> fix: fix settle and other issues

libs/src/clients/optimisticOracle/client.ts, libs/src/clients/optimisticOracleV2/client.ts, libs/src/constants.ts, libs/src/oracle-sdk-v1/services/optimisticOracleV2.ts, libs/src/oracle-sdk-v2/services/index.ts, libs/src/oracle-sdk-v2/services/oraclev2/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev2/ethers/index.ts, libs/src/oracle-sdk-v2/services/oraclev2/index.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/factory.ts, src/constants/env.ts, src/contexts/OracleDataContext.tsx
we want to be able to update the state of each oracle v2 request when user submits transactions
this adds oracle v2 receipt parsing when transactions complete, and updates global state of oracle data.  the logic is nearly identical to oracle v1 work, but i've separated it out as a different service to keep it easy to reason about. 
this also fixes a couple other issues
- identifying data in global state when its coming from a tx receipt is now fixed for oracle v1 requests
- wrong goerli address constant, we should probably verify all the constants eventually
=> feat: add oraclev2 log updates

src/helpers/converters.ts
The value text can be either the proposed price or the settlement price. Checking that they both exist will be false most of the time. The get value text function already handles potentially null values.
=> fix: remove exists check for value text

shared/constants/abi.ts, src/helpers/converters.ts, src/types/ui.ts
we want the ability to know if we have an og request, so that in the future we can show this in the ui
this adds the og abi in case we need to use it, currently its unused, since we can determine if its an og request by parsing ancillary data, to look for "rules:" and "explanation:".  this is not totally bulletproof but should get the job done. future implementations may require querying the og contract.   use the `isOptimisticGovernor` flag to add filters or badges in the UI.
=> feat: add isOptimisticGovernor option to ui query

src/components/OracleQueryTable/VerifyCells.tsx
currently we cant tell if things are disputed in the verify table
this just shows that request is disputed rather than showing ended
=> feat: show disputed in verify table

src/components/Pagination.tsx
Handle the case where the list of entries gets shorter, ensuring that the pagination component stays consistent with the updated entries.
- If the new entries list is empty, set the page number to 1 and update the entries to show.
- Calculate the new number of pages based on the updated entries and the current resultsPerPage.
- If the current page number is greater than the new number of pages, set the page number to the new last page, and update the entries to show.
- If the current page number is still valid, just update the entries to show without changing the page number.
=> handle entries number changing

src/components/InformationIcon.tsx, src/components/Panel/Panel.tsx, src/components/Tooltip.tsx, src/components/index.ts, src/stories/InformationIcon.stories.tsx
Add an `InformationIcon` component that can be dropped in to text content that needs further information.
This component wraps a tooltip and takes tooltip content as a prop.
It also wraps a button which shows the tooltip when clicked — this is so that on mobile (where hover events don't fire) the user can click the icon and still see the information.
[Story](https://63d101d13121a53332f6218c-yxryujdwnx.chromatic.com/?path=/story/stories-informationicon--default)
See it in action in the [Panel story](https://63d101d13121a53332f6218c-yxryujdwnx.chromatic.com/?path=/story/stories-panel--verify-with-dispute)
=> feat: add information icons

libs/src/oracle-sdk-v2/services/oraclev1/gql/queries.ts
we are missing some newish requests 
this orders requests by time descending, and only grabs the first 500 since the request tends to take a long time.
this does not apply to v3 assertions because there's no good value afaik to sort on
=> fix: query graph calls by time descending so we see newest

src/helpers/converters.ts
some dates are being reported incorrectly
looks like we were passing time in ms to a function that expected time in seconds, changed this to pass the correct time
=> fix: fix time formatting

src/components/Header/MobileMenu.tsx
When the user clicks one of the links in the mobile menu panel, close the panel.
=> fix: close panel on link clicked

libs/src/clients/skinnyOptimisticOracle/client.ts, libs/src/constants.ts, libs/src/oracle-sdk-v1/services/optimisticOracleV2.ts, libs/src/oracle-sdk-v1/services/skinnyOptimisticOracle.ts, libs/src/oracle-sdk-v1/types/interfaces.ts, libs/src/oracle-sdk-v2/services/index.ts, libs/src/oracle-sdk-v2/services/skinnyv1/ethers/factory.ts, libs/src/oracle-sdk-v2/services/skinnyv1/ethers/index.ts, libs/src/oracle-sdk-v2/services/skinnyv1/index.ts, shared/constants/oracle.ts, src/constants/env.ts, src/contexts/OracleDataContext.tsx
we want to be able to handle skinny oo updates when user submits transactions
this basically enables skinny oo ethers service configuration, copies most of the oo v1 ethers service in, and updates it to work with skinny oo calls. this is untested since we have no goerli subgraph for skinny oo, but it shouldnt break anything
=> feat: add skinny oo transaction handlers

public/assets/icons/chevron.svg, src/components/Panel/AdditionalTextData.tsx, src/components/Panel/Panel.tsx
add additional text data component
allow toggle show / hide of additional text data bytes
hide bytes by default
**[Story](https://www.chromatic.com/component?appId=63d101d13121a53332f6218c&csfId=stories-panel&buildNumber=62&k=64369dcff904555e8ae568af-320-interactive-true&h=38&b=-1)**
=> feat: toggle show / hide of bytes field

src/components/Currency.tsx
The existing implementation for the currency icon works fine, but React throws an error when we render a fragment and still pass a "content" prop to it. This doesn't matter in our case, but it throws many ugly errors and can easily be avoided.
=> fix: invalid prop passed to fragment error

src/hooks/actions.tsx
approvals break when user manually edits in metmask
this is due to gas limits changing when user changes approval amounts, causing out of gas issue, we double the calculated gas limit to prevent this. a better option would be to unset the limit, but types do not allow this, so a bignumber must be supplied.
=> fix: double gas limit for approvals

src/hooks/handleQueryInUrl.ts
we want to have backward compatible links with oracle v1 app, this requires routing to requests where urls are omitting the event index
this runs the routing logic even if event index is missing, and if we find multiple requests and omit event index, just return the first found
=> feat: allow url to omit event index, route to first query

src/components/TruncatedTitle.tsx
Even though we are enforcing a max length on titles, this can still break when the title contains long unbroken strings like addresses. By adding [`overflow-wrap: anywhere`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) we are able to "prevent overflow, an otherwise unbreakable string of characters — like a long word or URL — may be broken at any point if there are no otherwise-acceptable break points in the line".
=> fix: add overflow-wrap to truncated titles

src/components/Filters/Filters.tsx
The search bar component is not present in the filters mobile wrapper, which means the search bar does not show on mobile.
* Add the search bar component to the mobile wrapper
=> fix: search missing on mobile

public/assets/icons/clock.svg, public/assets/icons/info.svg, src/components/GlobalStyle.tsx, src/components/InformationIcon.tsx
Figma adds a redundant "clip path" to svgs a lot of the time for reasons I can't quite understand. This breaks the svgs on smaller screens quite often. I've removed them from a couple here that I missed in my last pass through.
=> fix: svg render on mobile

src/components/OracleQueries.tsx
Use a function initializer for the is loading state, which is persisted between renders, to avoid re-rendering with the loading state as `true` on first render.
=> fix: flash of loader when content is loaded

src/components/CheckboxDropdown.tsx, src/components/DecimalInput.tsx, src/components/OracleQueryList/ItemDetails.tsx, src/components/OracleQueryTable/SettledCells.tsx, src/components/OracleQueryTable/VerifyCells.tsx, src/components/Panel/Actions/Actions.tsx, src/components/Panel/Actions/ProposeInput.tsx, src/components/RadioDropdown.tsx, src/components/style.tsx, src/helpers/converters.ts, src/helpers/converters.tsx, src/helpers/queryParsing.ts, src/helpers/util.ts, src/hooks/index.ts, src/hooks/proposePriceInput.ts, src/types/ui.ts
The projects that we specifically handle are defined as:
`export const projects = [
"Unknown",
"Polymarket",
"Cozy Finance",
"Across",
"Sherlock",
"OSnap",
] as const;`
Of these, Sherlock does not appear in the UI because of how their flow works (they do everything in a single transaction). 
OSnap only runs on OOv3, and therefore their assertions will never end up on the propose page and don't need to have inputs. I have however added some logic for parsing the description from the OSnap claim data.
Polymarket has logic that has been copied wholesale from the voter dapp.
Cozy Finance and Across both use a simple yes = 1 no = 0 logic and can therefore have the options:
`[
{ label: "Yes", value: "1", secondaryLabel: "1" },
{ label: "No", value: "0", secondaryLabel: "0" },
]`
=> feat: parse results for projects

src/components/Panel/Actions/PrimaryActionButton.tsx, src/hooks/actions.tsx
When setting `disabled: true` on the primary action button, also include a `disabledReason` string that can be shown in a tooltip.
=> feat: show tooltips for disabled buttons

src/components/OracleQueryTable/ProposeCells.tsx, src/helpers/converters.tsx
final fee was not included in bond, some people were not seeing they would be debited more than what was shown on ui
this makes sure final fee gets added to bond in all tables
before
after
=> fix: add final fee to bond

src/hooks/filters.ts
The Fuse fuzzy search library has a default setting where it wants the search string to appear at the start of the search text. This is not what we want because we want to be able to find things anywhere in the string. By setting `ignoreLocation` to true, the search looks throughout the whole string instead.
=> fix: add ignore location to fuse config

shared/utils/graphql.ts, src/contexts/OracleDataContext.tsx, src/helpers/util.ts, src/stories/mocks.tsx, src/stories/pages/Verify.stories.tsx
Sort verify page queries by liveness ends when loading them in the OracleDataContext.
**[Story](https://www.chromatic.com/component?appId=63d101d13121a53332f6218c&csfId=pages-verify--with-different-expirations&buildNumber=71&k=64464506865ea7d129a70eb6-320-interactive-true&h=12&b=-4)**
=> fix: sort verify page queries by liveness ends

src/components/OracleQueryList/OracleQueryList.tsx, src/components/OracleQueryTable/OracleQueryTable.tsx, src/components/Pagination.tsx, src/components/index.ts, src/stories/Pagination.stories.tsx
This bug was caused by this logic:
`const [rowsToShow, setRowsToShow] = useState(rows);`
Using the `rows` as the initial state means that the component is first rendered with the entire list of unpaginated values. This first render happens before the `Pagination` component has a chance to render, which means that we attempt to render all several thousand of the entries on the first render.
Changing the code to:
``const [rowsToShow, setRowsToShow] = useState(rows);``
Fixes the issue. 
However, this component's api is in my opinion going to be a source of bugs, because the `entriesToShow` logic is duplicated in the components that use it, and its certainly possible that it would happen again in another usage of the component.
I've opted to change the api of the component, so that its now …
=> fix: add usePagination hook to avoid wrong initial values

src/components/LivenessProgressBar.tsx
we had a mispelling of minutes
turns out the regex for "m(onth)?" was matching with minutes because the second block was optional, this changes regex to match the full word with only the `s` optional
=> feat: fix regex for shortening time units

src/constants/filters.ts, src/hooks/filters.ts
if trying to search large strings, the site locks up on settled page since there are so many entries and long strings
this removes some redundant search fields which contain long strings, related to ancillary data, and adds a debounce for the input box so search is not executed on every change, it waits 500ms for user to stop typing.
=> improve: prevent site locking from search

src/components/ChainNameAndIcon.tsx, src/components/OracleQueryList/ItemTitle.tsx, src/components/OracleQueryTable/TitleCell.tsx, src/components/index.ts
Add a `ChainNameAndIcon` component that shows a chain's icon next to its name.
=> feat: include chain icon in table

libs/src/oracle-sdk-v2/services/oracles/factory.ts, libs/src/oracle-sdk-v2/services/oraclev1/gql/factory.ts, libs/src/oracle-sdk-v2/services/oraclev1/gql/queries.ts, libs/src/oracle-sdk-v2/services/oraclev3/gql/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/gql/queries.ts, shared/types/oracle.ts, src/components/ErrorMessage.tsx, src/contexts/ErrorContext.tsx, src/contexts/OracleDataContext.tsx, src/pages/_app.tsx, src/stories/ErrorBanner.stories.tsx, src/stories/pages/types.ts, src/types/ui.ts
Pass down an `addErrorMessage` function from the `ErrorContext` to the graphql queries so that they can show a global error in the event of a graph outage like the planned one coming up on Monday.
We don't know if the graph will simply throw a 500 error during this downtime, or if it will return an errors object like it normally would in the case of a query error. I've updated the functions to handle both cases.
=> feat: handle graph failures in queries

libs/src/clients/optimisticOracleV3/client.ts, libs/src/oracle-sdk-v2/services/oracles/factory.ts, libs/src/oracle-sdk-v2/services/oraclev1/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev1/gql/factory.ts, libs/src/oracle-sdk-v2/services/oraclev1/gql/queries.ts, libs/src/oracle-sdk-v2/services/oraclev2/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/gql/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/gql/queries.ts, libs/src/oracle-sdk-v2/services/skinnyv1/ethers/factory.ts, libs/src/utils.ts, src/constants/env.ts, src/contexts/OracleDataContext.tsx
we had a critical time where our subgraph was down, but we also needed to dispute a proposal. we need a way to query providers as a backup in case the graph goes down.
this adds a feature to each ethers service to query based on a number of blocks ago. it will automatically be called if any of the graphs throw an error during querying. appropriate error messages will be displayed if this happens, alerting the user the site experience may be degraded. 
this is difficult to test, you wil most likely need to checkout locally and edit your .env files to point to incorrect graph urls. this will trigger the fallback.
by default all lookback limits are set to 100000.  this may not be appropriate for all networks, if its a problem we can update these values per network and graph at a future …
=> feat: add web3 fallback for querying data if graph down

libs/src/oracle-sdk-v2/services/oraclev3/gql/queries.ts, src/contexts/OracleDataContext.tsx
we are seeing gql error banners frequently since we implemented fallback system. this is because we want to know when we are using web3 fallbacks. currently we dont know why the banners are showing up so much
this adds more general logging for any errors that happen when querying data. this will only log to console. after some inspection it looks like its the polygon subgraph failing, which may be due to the size of the queries. we also reduce the size to see if that helps prevent failures to the subgraph
=> improve: logging and reduce gql query size

shared/constants/abi.ts, src/components/Panel/Details.tsx, src/components/Panel/RatedAssertionTextData.tsx
We should show the report data as acquired from the rated oracle contract in the panel.
* fetch the report and violations from the contract
* show this instead of the additional text data for these requests
Testing:
I can't seem to find the goerli transaction that they used as an example in the oracle ui. hardcoded that value ("5") just to see that everything is fetched and displayed correctly, and I can confirm that it is.
=> improve: enrich rated assertions with data from their contract in ui

src/components/Panel/RatedAssertionTextData.tsx
I accidentally took out the report number. Add it back in.
=> improve: add report number to rated assertions

src/components/Notifications.tsx, src/components/RadioDropdown.tsx, src/components/Tooltip.tsx, src/components/style.tsx, src/stories/Panel.stories.tsx
When I converted the panel to tailwind, I overlooked an implementation detail: for reasons I'm not so sure about, [tailwind specifies z indexes in multiples of 10](https://tailwindcss.com/docs/z-index#setting-the-z-index).
In the rest of the app, we count z index in increments of 1. I had the panel set to z index of 1, and the dropdown to a z index of 2.
This meant that when I changed the panel to tailwind and gave it tailwind's equivalent of z  index 1, which is actually z index 10, it broke the implementation by making it a higher z index than that of the dropdown and caused the dropdown to be hidden behind the panel.
I missed this because I did not have a storybook example with the dropdown input for the propose state, which has now been rectified.
I have updated all the other z …
=> fix: dropdown z index

src/components/Panel/AdditionalTextData.tsx, src/components/Panel/style.tsx
Add the `break-words` property to the description <p> tags so that they are allowed to break long text like addresses and hashes.
=> fix: add break words to p tags

src/helpers/queryParsing.ts
polymarket updated ancillary data which slightly affects dropdown parsing. preivously all data would end with a comma, now its possible they end with a period. small change but this breaks drop down option parsing.
this alters the regex to end on a comma or period, to make sure it fixes future requests and still works with past requests
and older request
=> fix: allow dropdowns to end parsing with , or .

src/hooks/actions.tsx
theres a bunch of expired proposals that cant be settled on testnet for example: https://testnet.oracle.umaproject.org/?chain=5&transactionHash=0x95970c9252a4e1254aba892c81556d613b39e7c8fa92b365d00a69e20a226f5f&eventIndex=10
we were not correctly gaurding the dispute function when action type was set to "settle".  this exits so settle code can correctly take over
=> fix: dont show disputed when settle is available

src/app/page.tsx
we dont want to see oracle "v2" anymore
remove v2
=> improve: remove oracle v2 titles

src/helpers/queryParsing.ts
there are some yes no query identifiers not showing the right  option selections in details page
this adds a simple yes/ no dropdown if it detects a yes no identifier
=> fix: show yes no dropdown for yes no query

src/components/Panel/Actions/Errors.tsx, src/helpers/util.ts
closes #UMA-1934
Wagmi egnerally does a good enough job of parsing/decoding any revert or error messages that might be thrown while attempting to interact with a contract. But in some cases there is either no sighash or string associated with the revert and in those cases the provider throws an "Internal JSON RPC error" along with the stringified blob of transaction data. 
This is a huge chuck of text and is not helpful to the user since all it's saying it "Cannot estimate gas" because we the provider was unable to simulate the transaction successfully. 
In these cases we want to simply replace this chunk of text with a generic message like "Transaction Failed".
=> replace unhelpful "cannot estimate gas" error message

shared/utils/ethers.ts, src/components/Notification.tsx
closes #UMA-1933
If a transaction happens on chain X, we want to have a label that says "View on `<BLOCK_EXPLORER_FOR_CHAIN>`"
=> feat: get block explorer label for each chain

src/helpers/queryParsing.ts
The app now parses p1/p2 proposals (no p3) and shows a dropdown in this case.
=> feat: allow commas in p0 & p1 res

libs/src/oracle-sdk-v2/services/oraclev1/gql/queries.ts, src/contexts/OracleDataContext.tsx
apprently the graph does not let us skip more than 5k items, which we now have more than
uses recommended query "where" on object property time, which seems to do the trick for everything after 5k
=> fix: allow more than 5k gql queries for oov1/2

libs/src/constants.ts, shared/constants/oracle.ts, src/helpers/converters.ts, src/helpers/queryParsing.ts
we want to be more specific when identifying polymarket requests for labeling the project
uses known polymarket requester addresses to further filter requests https://github.com/UMAprotocol/optimistic-oracle-dapp-v2/pull/new/david/uma-2440-detect-project-using-requester-address
=> feat: filter polymarket by requester address

libs/src/types.ts, src/components/Panel/Actions/Actions.tsx, src/components/Panel/TenderlySimulation.tsx, src/helpers/snapshot.ts, src/types/snapshot.ts
We want to let oSnap users know that they are missing out on Tenderly Sim functionality if they are using the legacy safeSnap plugin.
=> feat: show migration banner if using legacy plugin

src/helpers/queryParsing.ts
we want to add umip 181 mutliple choice query support
adds a decoder and parser to fetch title, descriptiton and options
=> feat: add multiple_choice_query parsing

src/helpers/queryParsing.ts, src/hooks/actions.tsx
currently the UI is treating values specified in mutliple choice options as ETH, so when they are proposed they get converted to wei. this is incorrectly they shoudl be interpreted as wei and not have any scaling.  this is difficult because all values have been assumed to be specified as eth in the app.
this converts value the user provides to a decimal as eth, so when it gets converted back downstream it properly converts back to the original wei value, ie 5e17 gets converted to .5 as the value, then on proposal this gets converted back to 5e17
=> fix: fix multiple choice values to be proposed as wei

src/components/Panel/Actions/Errors.tsx
Any unbroken strings (like addresses) would overflow its container. this is default css.
Here we ensure to break long words to prevent this from happening.
=> fix: prevent unbroken strings from overflowing error container

src/helpers/converters.ts
There is an issue with showing settled values for multiple choice identifier
This should show O2, which has a settled value of 1 wei.
We have to make a special case for the mutliple choice query identifier when calculating value text.
=> fix: special case MCQ identifier for parsing values

src/components/Panel/PolymarketTextData.tsx, src/helpers/converters.ts, src/helpers/queryParsing.ts
fixes UMA-2611
It can be difficult to make voting decisions based on timing, when dates and times are displayed in different time zones. In this PR we use UTC time ion the Polymarket Bulletin board instead of local time.
=> use UTC date-time in polymarket bulletin board

libs/src/clients/optimisticOracleV2/client.ts, libs/src/clients/skinnyOptimisticOracle/client.ts, libs/src/oracle-sdk-v1/services/optimisticOracleV2.ts, libs/src/oracle-sdk-v2/services/oraclev2/ethers/factory.ts, shared/types/graphql.ts, shared/types/oracle.ts
fixes UMA-2644
When a subgraph is down we resort to fetching request data directly from the chain. We do this first by fetching events from the OO, namely: `RequestPrice` , `ProposePrice`, `DisputePrice` & `Settle`.
For the OOv2 we SUM the bond and finalFee amounts. And when fetching dat like this ONLY rom events, we do not have the bond amount, only the final fee, thus causing teh bug that displays the full bond as only the final fee amount.
This PR ensure that, in the case of a subgraph outage, we first fetch event data, but also get updated data for each request by calling `getRequest()` on the OO.
=> fix: update incomplete event data with direct reads from contract

src/components/Panel/Actions/Actions.tsx
1. Go to propose page, open side panel by clicking on a query
2. make sure wallet in DISCONNECTED
3. See that the input is NOT DISABLED
4. Connect wallet.
5. Switch to incorrect chain.
6. See that the input is still NOT DISABLED
=> fix: don't disable proposal input if not connected or wrong chain

src/helpers/util.ts, src/hooks/actions.tsx
closes UMA-2180 UMA-2659
The oracle dapp displays some pretty large and unhelpful revert/error messages if a user attempts to propose/dispute/settle any assertions that have already been proposed/dispued/asserted.
This PR ensures we format the revert and error messages both in the tooltip (if button is disabled and preparation for the action failed) as well as in the red error container below the action panel in the case that the preparation succeeded so the user was able to submit a failing transaction.
=> feat: format cryptic errors when proposing an already proposed request

libs/src/utils.ts, src/helpers/converters.ts, yarn.lock
We want users to be able to find osnap requests easier, at a glance. This PR extracts the space name from the request data and adds it to the title.
=> add space name to osnap request titles

.gitignore, src/helpers/queryParsing.ts
There was a broken polymarket market due to badly formatted ancillary data. added another unique condition to correctly parse it
=> fix: add condition for unique polymarket formatting

shared/constants/oracle.ts, src/constants/wallet.ts
we are seeing chain not supported when connected on base sepolia, though we should support it
this makes sure the wallet lib knows we are allowing it
=> fix: whitelist base sepolia

src/components/Currency.tsx, src/constants/tokens.ts, src/hooks/actions.tsx
closes UMA-2772
- add mapping to resolve bridged usdc symbol (`chainID => tokenAddress => tokenSymbol`)
=> resolve USDC.e for polygon

src/hooks/actions.tsx
closes UMA-2773
- wait until bond is approved before we simulate any write functions that would revert if not approved
=> defer action simulations until bond is approved

libs/src/oracle-sdk-v2/client.ts, libs/src/oracle-sdk-v2/services/oraclev1/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev2/ethers/factory.ts, libs/src/oracle-sdk-v2/services/oraclev3/ethers/factory.ts, libs/src/oracle-sdk-v2/services/skinnyv1/ethers/factory.ts, src/contexts/OracleDataContext.tsx, src/hooks/actions.tsx, src/hooks/useQueryInSearchParams.ts
we want to speed up loading when directed to a single request by tx hash
this exposes a new function on oov2 ethers services to load something by a tx hash, currently only enabled on oov2 because polymarket needs the most optimization 
go to settled or proposed tab, choose a really old request, copy url and load it into an incognito window to see how fast it loads the details panel.  try this with the prod site to compare speed
=> feat: add individual request query for details page

libs/src/oracle-sdk-v2/services/oraclev2/ethers/factory.ts
highlighted area should not show if not in verify phase
if expiration time is set to 0, leave it undefined in data
=> fix: hide expiration time if set to 0

libs/src/oracle-sdk-v2/services/oraclev1/gql/factory.ts
since introducing incremental loading, pages seem to be really frozen
this goes back to one shot loading. incremental loading was introduced to speed up landing on specific requests, but this was fixed with a more targeted change, so we can try to go back to how we were loading before, which was buffer everything then render when done, vs incrementally rendering in batches
=> fix: go back to single shot load for gql requests

src/hooks/useQueryInSearchParams.ts
we are still colliding with some request urls
we scale the event log score according the the transaction match type. sorry this is a bit opaque, but it seems to solve the issue for now
=> fix: improve weights url search scorer

src/components/Header/Title.tsx, src/constants/env.ts, src/contexts/OracleDataContext.tsx, src/hooks/queries.ts
improve loading speed of settled page
this limits lookback to 5k settled requests which significantly speeds up loading
test a specific request wiht this query from 2022: 
`/settled?transactionHash=0x25fa9cc18c2ff800776a7e037ce6a332901dfc30add06f2bb1e6640f3a378c35&eventIndex=5`
=> improve: set limit on settled page requests

shared/utils/ethers.ts, src/helpers/converters.ts
Fix: Preserve Exact Precision for Proposal Price Display
When displaying unscaled proposal prices (e.g., `1` which should be `1000000000000000000` in wei), the UI was incorrectly truncating decimals during the display formatting process. This caused issues when trying to match prices against ancillary data, as the exact precision was being lost.
- Retain 18 decimals of precision when scaling price.
Incorrect display [OO Proposal](https://oracle.uma.xyz/?transactionHash=0xae7354ab83366edf0dbe231607ce6095b8b80f1b539058833574eade370654c2&chainId=137&oracleType=OptimisticV2&eventIndex=141)
Correct Display [OO Proposal](https://optimistic-oracle-dapp-v2-git-fix-do-not-truncate-in-ce1c3b-uma.vercel.app/?transactionHash=0xae7354ab83366edf0dbe231607ce6095b8b80f1b539058833574eade370654c2&chainId=13 …
=> do not round when scaling proposed prices

src/hooks/proposePriceInput.ts, src/identifiers/Numerical.ts, src/identifiers/YesOrNoQuery.ts, src/identifiers/index.ts
closes UMA-2905
- Added custom parsing logic for `NUMERICAL` identifiers
- Implemented logic to parse ancillary data
- Added functionality to generate propose options for requests
- Added new options to the YES_OR_NO_QUERY identifier:
- Unknown (50/50) option
- Custom input option
- Updated default fallback propose options for cases when a request's identifier is not found in approved identifiers list
- Fixed input handling: Propose price value now clears when switching from dropdown to custom input mode
These are the same request. 
- Current [Numerical request](https://oracle.uma.xyz/?transactionHash=0x45ced4fcb7226e5da1eeca10b536f5019939489952f92e5b41a6bfe6dddb9777&eventIndex=106)
- Improved [Numerical request](https://optimistic-oracle-dapp-v2-git-feat-numerical-uma.vercel.app/?transact …
=> Feat numerical

src/components/Panel/Title.tsx, src/projects/abstract.ts, src/projects/polymarket.ts
closes UMA-2912
1. Adds Polymarket's [UmaCTFAdapter](0x157Ce2d672854c848c9b79C49a8Cc6cc89176a49) contract as requester address.
2. When matching a request to a project, if we match an initialzier address, then match the project to the request without performing other checks
=> Add Polymerket requester address
